name: Change tests

on:
  pull_request:
    branches:
      - main
      - next
  push:
    branches:
      - main
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  python_pyodide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: '**/requirements.dev.txt'

      - run: pip install pyodide-build
      - shell: bash
        run: |
         echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV
         echo PYTHON_VERSION=$(pyodide config get python_version | cut -d "." -f 1-2) >> $GITHUB_ENV
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}
          actions-cache-folder: emsdk-cache

      - shell: bash
        # rust version is pinned for compatibility with emscripten 3.1.58
        run: |
          cd python
          pip install maturin
          rustup install nightly-2025-02-01
          rustup default nightly-2025-02-01
          rustup target add wasm32-unknown-emscripten
          pyodide build
